#!/usr/bin/env bash

echo "Pindah kebranch main dan update main"
git switch main
git pull origin main

branches=("randy" "farid" "hafizh" "kirana" "tiara")
for branch in "${branches[@]}"; do
  echo "menggabungkan main ke $branch..."
  git switch "$branch"
  git pull origin "$branch"
  echo "Melakukan merge pada $branch..."
  git merge main
done

git switch main
echo "Merge selesai"
